\\depot.engr.oregonstate.edu\users\sanfordc\Windows.Documents\Desktop\ME497 CAD\Payload-CAD\ARRD Attatchment\top solenoid plate-Static 1
\\depot.engr.oregonstate.edu\users\sanfordc\Windows.Documents\Desktop\ME497 CAD\Payload-CAD\ARRD Attatchment\top solenoid plate-Static 1
\\depot.engr.oregonstate.edu\users\sanfordc\Windows.Documents\Desktop\ME497 CAD\Payload-CAD\ARRD Attatchment\top solenoid plate-Static 1
